feat(addJudgePage) create front end
acmutd/jury pull request #24
Opened 2023-04-18 03:14 UTC by thetechie7

### Description

[Describe the issue that this fixes or the feature that this adds]
Designed the Add Judges Page using Figma

### Fixes #14

### Type of Change

Delete options that do not apply:

- New feature (non-breaking change which adds functionality)

### Is this a breaking change?

- [ ] Yes
- [*] No

2023-04-26 04:35 UTC, MichaelZhao21 commented
@thetechie7 I added the endpoints u need:

* POST `/api/judge/csv` - `Content-Type=multipart/form-data` with a single `csv` field that contains the CSV file uploaded
* POST `/api/judge/add` - `Content-Type=json` - with 3 fields:

```json
{
    "name": "name of judge",
    "email": "email of judge",
    "notes": "additional notes"
}
```

2023-05-15 20:26 UTC, MichaelZhao21 commented
The errors don't clear when you upload new files.

2023-05-15 20:27 UTC, thetechie7 commented
oh no let me fix that

2023-05-15 20:28 UTC, MichaelZhao21 requested changes

2023-05-15 22:07 UTC, MichaelZhao21 approved these changes

2023-05-15 22:08 UTC, merged